### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getProtection()I in class Landroid/content/pm/PermissionInfo

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken/mystic-permissions#25]
It works now, it doesn't crash at start [(Issue #8)](https://github.com/d4rken/mystic-permissions/issues/8).

But when i do this:
Wait for apps to load>tap any app>tap a permission, it crashes, it supposed to open the app's permission settings page

On Permissions tab, when i tap a permission on Permissions tab, it supposed to list apps that uses that perm, but it just crashes

(I'll upload a log tomorrow or the day after)

**Comment by TheMysticS** [comment]
Doesn't crash on my device (Android 12). Can you delete app data and start afresh to see if it happens?

**Comment by dragonGod97677** [comment]
> Doesn't crash on my device (Android 12). Can you delete app data and start afresh to see if it happens?

Nah, still same, seems device compatibility issue

**Comment by TheMysticS** [comment]
> > Doesn't crash on my device (Android 12). Can you delete app data and start afresh to see if it happens?
> 
> We need this app compatible to all phones and tablets
>
Sure.

**Comment by dragonGod97677** [comment]
> > > Doesn't crash on my device (Android 12). Can you delete app data and start afresh to see if it happens?
> > 
> > 
> > We need this app compatible to all phones and tablets
> 
> Sure. Which ROM are you using?

Stock Oppo A3s ROM

**Comment by d4rken** [comment]
Need the stacktrace to fix this :coffee:

**Comment by TacoTheDank** [comment]
@d4rken I'm not sure if this is the exact issue they're talking about, but I get this crash at runtime (version 0.2.0):

```
FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: eu.darken.myperm, PID: 16028
java.lang.NoSuchMethodError: No virtual method getInstallSourceInfo(Ljava/lang/String;)Landroid/content/pm/InstallSourceInfo; in class Landroid/content/pm/PackageManager; or its super classes (declaration of 'android.content.pm.PackageManager' appears in /system/framework/framework.jar)
	at eu.darken.myperm.apps.core.installer.InstallerInfoKt.getInstallerInfoLegacy(InstallerInfo.kt:69)
	at eu.darken.myperm.apps.core.installer.InstallerInfoKt.getInstallerInfo(InstallerInfo.kt:54)
	at eu.darken.myperm.apps.core.AppRepo.toDefaultApp(AppRepo.kt:82)
	at eu.darken.myperm.apps.core.AppRepo.access$toDefaultApp(AppRepo.kt:26)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invokeSuspend(AppRepo.kt:43)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:8)
	at eu.darken.myperm.apps.core.AppRepo$apps$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6b0b2cc, Dispatchers.Default]
```

**Comment by dragonGod97677** [comment]
[version 0.1.2 crash logs](https://github.com/d4rken/mystic-permissions/files/9132739/0.1.2.zip)

**Comment by dragonGod97677** [comment]
[v0.2.0-20000-FOSS-RELEASE-6215ceb](https://github.com/d4rken/mystic-permissions/files/9132799/v0.2.0-20000-FOSS-RELEASE-6215ceb.txt)

**Comment by d4rken** [comment]
Is the same as #32 actually.

Should be fixed with 0.2.1, can you confirm?

**Comment by dragonGod97677** [comment]
> Is the same as #32 actually.
> 
> Should be fixed with 0.2.1, can you confirm?

Already downloaded it few minutes ago, gonna do fresh install and will do report, be right back

**Comment by dragonGod97677** [comment]
Okay, so the version i have installed and tested now is 0.2.2-20200-FOSS-RELEASE-2277cd4

Still the same
Wait for apps to load>tap any app>tap a permission, it crashes, it supposed to open the app's permission settings page

On Permissions tab, when i tap a permission on Permissions tab, it supposed to list apps that uses that perm, but it just crashes

[4 Crash Logs](https://github.com/d4rken/mystic-permissions/files/9133015/4.Crash.Logs.Of.0.2.2-20200-FOSS-RELEASE-2277cd4.zip)

**Comment by d4rken** [comment]
Api level 28:
https://developer.android.com/reference/android/content/pm/PermissionInfo#protectionLevel

**Comment by d4rken** [comment]
> Is this saying that getProtection() is missing on my device's rom?

Yes but not because of OPPO, but because it's only available on Android 9+.
I've fixed it though, new build coming...

**Comment by d4rken** [comment]
> Oh wow, it's okay now, thanks

Sorry it took so long :heart:  now you can help test too :yum:
